<?php
/**
 * @package  GinkGos
 * @Version 0.0.1
 */
return array(
    'polylang-dropdown'                 => false,
    'polylang-show-names'               => true,
    'polylang-show-names-slug'          => true,
    'polylang-show-flags'               => false,
    'polylang-hide-if-empty'            => true,
    'polylang-hide-if-no-translation'   => false,
    'polylang-hide-current'             => false,
    'contact-google-maps'               => true,
    'contact-address'                   => true,
    'contact-address-street'            => 'Av. des Champs-Élysées',
    'contact-address-city'              => '75000 paris',
    'contact-address-country'           => 'France',
    'contact-phone'                     => true,
    'contact-phone-name'                => 'Dupont Dupond',
    'contact-phone-number'              => '+33 123 456 789',
    'contact-phone-time'                => 'Mon – Fri, 9:00-18:00',
    'contact-email'                     => true,
    'contact-email-name'                => 'Dupont Dupond',
    'contact-email-address'             => 'dupont.dupond@dupond.com',
    'contact-legal-info'                => true,
    'contact-legal-info-name'           => 'Dupont Dupond Co.',
    'contact-legal-info-text-1'         => 'Fiscal Code: 123456789',
    'contact-legal-info-text-2'         => 'VAT: 0123456789',
    'body-color-text'                   => '#5c5c5c',
    'body-color-background'             => '#e5e5e5',
    'body-color-main'                   => '#fff',
    'body-color-link'                   => '#ce9e27',
    'post-title-color'                  => '#5c5c5c',
    'navigation-fix-to-top'             => false,
    'navigation-border-color'           => '#ddd',
    'back-to-top-enable'                => false,
    'back-to-top-arrow'                 => 'fa-angle-double-up',
    'back-to-top-background'	        => '#5c5c5c',
    'back-to-top-background-hover'	    => '#5c5c5c',
    'back-to-top-color'	                => '#CE9E27',
    'progress-bar-enable'	            => false,
	'progress-bar-bubble'               => true,
    'progress-bar-color'                => '#ffffff',
	'progress-bar-background'           => '#48add8',
	'progress-bar-background-completed' => '#83bd71',
);