<?php
/**
 * @package ginkgos
 * @since 0.0.1
 */

return array(
    array(
        'name'      => GINKGOS_NAME . '-contact',
        'type'      => 'section',
        'title'      => __( 'Contact', 'ginkgos' ),
        'panel'      => 'ginkgos_theme_option',
        'capability' => 'edit_theme_options',
        'priority'   => 50,
    ),
    array (
        'name'      => 'contact-heading',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-heading',
        'title'     => __( 'Please add modele "Contact Form" in your page contact and display this. ', 'ginkgos' ),
    ),
    array (
        'name'      => 'contact-google-maps',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-on-off',
        'title'     => __( 'Enable Map on contact form.', 'ginkgos' ),
        'default'   => self::get_option('contact-google-maps'),
    ),
    array (
        'name'      => 'contact-address-sep',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-divider',
    ),
    array (
        'name'      => 'contact-address',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-on-off',
        'title'     => __( 'Display contact address.', 'ginkgos' ),
        'default'   => self::get_option('contact-address'),
    ),
    array (
        'name'      => 'contact-address-street',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Street', 'ginkgos' ),
        'default'   => self::get_option('contact-address-street'),
    ),
    array (
        'name'      => 'contact-address-city',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'City', 'ginkgos' ),
        'default'   => self::get_option('contact-address-city'),
    ),
    array (
        'name'      => 'contact-address-country',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Country', 'ginkgos' ),
        'default'   => self::get_option('contact-address-country'),
    ),
    array (
        'name'      => 'contact-phone-sep',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-divider',
    ),
    array (
        'name'      => 'contact-phone',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-on-off',
        'title'     => __( 'Display phone.', 'ginkgos' ),
        'default'   => self::get_option('contact-phone'),
    ),
    array (
        'name'      => 'contact-phone-name',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Name', 'ginkgos' ),
        'default'   => self::get_option('contact-phone-name'),
    ),
    array (
        'name'      => 'contact-phone-number',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Number', 'ginkgos' ),
        'default'   => self::get_option('contact-phone-number'),
    ),
    array (
        'name'      => 'contact-phone-time',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Time', 'ginkgos' ),
        'default'   => self::get_option('contact-phone-time'),
    ),
    array (
        'name'      => 'contact-email-sep',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-divider',
    ),
    array (
        'name'      => 'contact-email',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-on-off',
        'title'     => __( 'Display email.', 'ginkgos' ),
        'default'   => self::get_option('contact-email'),
    ),
    array (
        'name'      => 'contact-email-name',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Name', 'ginkgos' ),
        'default'   => self::get_option('contact-email-name'),
    ),
    array (
        'name'      => 'contact-email-address',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Address', 'ginkgos' ),
        'default'   => self::get_option('contact-email-address'),
    ),
    array (
        'name'      => 'contact-email-desc',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-description',
        'title'     => __( 'Email addresse use in form ', 'ginkgos' ),
    ),
    array (
        'name'      => 'contact-legal-info-sep',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-divider',
    ),
    array (
        'name'      => 'contact-legal-info',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'ginkgos-on-off',
        'title'     => __( 'Display legal Informations.', 'ginkgos' ),
        'default'   => self::get_option('contact-legal-info'),
    ),
    array (
        'name'      => 'contact-legal-info-name',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Name', 'ginkgos' ),
        'default'   => self::get_option('contact-legal-info-name'),
    ),
    array (
        'name'      => 'contact-legal-info-text-1',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Text 1', 'ginkgos' ),
        'default'   => self::get_option('contact-legal-info-text-1'),
    ),
    array (
        'name'      => 'contact-legal-info-text-2',
        'type'      => 'control',
        'section'   => GINKGOS_NAME . '-contact',
        'control'   => 'text',
        'title'     => __( 'Text 2', 'ginkgos' ),
        'default'   => self::get_option('contact-legal-info-text-2'),
    ),
);